import {test,expect} from '@playwright/test';
import fs from 'node:fs';
const book=JSON.parse(fs.readFileSync('public/ebook-a.json','utf8'));
test.beforeEach(async({page})=>{await page.goto('./#ebook-a');await expect(page.getByRole('heading',{name:'Học từ vựng qua e-book A'})).toBeVisible();});
async function study(page,n=1){await page.getByRole('button',{name:'Tiếp tục học theo thứ tự',exact:true}).click();for(let i=0;i<n;i++){await page.getByRole('button',{name:'Lật thẻ · Xem nghĩa và ví dụ'}).click();await page.getByRole('button',{name:'Đã học · Lưu và tiếp tục'}).click();}await page.getByRole('button',{name:'Đóng',exact:true}).click();}
test('ebook ordered study autosaves typed notes on continue, survives reload, remains separate, and gates every option',async({page})=>{
 await page.getByRole('tab',{name:'Ôn tập & trò chơi'}).click();await expect(page.getByRole('button',{name:/Lật thẻ ghi nhớ/})).toBeDisabled();
 await page.getByRole('tab',{name:'Lộ trình học'}).click();await expect(page.locator('.ebook-word-list button').nth(1)).toBeDisabled();
 await page.getByRole('button',{name:'Tiếp tục học theo thứ tự',exact:true}).click();await expect(page.getByRole('button',{name:'Đã học · Lưu và tiếp tục'})).toHaveCount(0);
 await page.getByRole('button',{name:'Yêu thích',exact:true}).click();await page.getByRole('button',{name:'Lật thẻ · Xem nghĩa và ví dụ'}).click();await page.getByLabel('Ghi nhớ riêng của tôi').fill('Mẹo nhớ riêng: nguy hiểm lớn.');await page.getByRole('button',{name:'Đã học · Lưu và tiếp tục'}).click();
 await expect(page.getByRole('dialog')).toHaveAttribute('aria-label','E-book A · Mục 2/826');await page.getByRole('button',{name:'Lật thẻ · Xem nghĩa và ví dụ'}).click();await page.getByRole('button',{name:'Đã học · Lưu và tiếp tục'}).click();await page.getByRole('button',{name:'Đóng',exact:true}).click();
 await page.reload();await expect(page.locator('.ebook-hero')).toContainText('Mục 3/826');
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('vua-english-v1')||'null')?.cards||{})).toEqual({});
 await page.locator('.ebook-word-list button').first().click();await page.getByRole('button',{name:'Lật thẻ · Xem nghĩa và ví dụ'}).click();await expect(page.getByLabel('Ghi nhớ riêng của tôi')).toHaveValue('Mẹo nhớ riêng: nguy hiểm lớn.');await page.getByRole('button',{name:'Đóng',exact:true}).click();
 await page.getByRole('tab',{name:'Ôn tập & trò chơi'}).click();await page.getByRole('button',{name:/Chọn nghĩa đúng/}).click();
 for(let i=0;i<2;i++){const word=await page.locator('.ebook-practice>h2').textContent();const w=book.words.slice(0,2).find(w=>w.word===word);expect(w).toBeTruthy();expect(await page.locator('.ebook-options button').allTextContents()).toEqual(expect.arrayContaining(book.words.slice(0,2).map(w=>w.meaning)));await expect(page.locator('.ebook-options button')).toHaveCount(2);await page.locator('.ebook-options').getByRole('button',{name:w.meaning,exact:true}).click();await page.getByRole('button',{name:i===1?'Xem kết quả':'Tiếp theo',exact:true}).click();}
 await expect(page.getByText('Đã lưu lượt ôn trên máy')).toBeVisible();await page.getByRole('button',{name:'Về e-book A'}).click();await page.getByRole('tab',{name:'Bộ nhớ & lịch sử'}).click();await expect(page.locator('.ebook-history li')).toHaveCount(6);
});
test('ebook backups merge idempotently into a fresh device and reject invalid backups',async({page,browser})=>{
 await study(page,2);await page.getByRole('tab',{name:'Bộ nhớ & lịch sử'}).click();const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Xuất bản sao e-book A'}).click()]);const backup=fs.readFileSync(await download.path());const data=JSON.parse(backup);expect(data.cards.filter(c=>c.learnedAt)).toHaveLength(2);
 const context=await browser.newContext(),other=await context.newPage();await other.goto(page.url());await other.getByRole('tab',{name:'Bộ nhớ & lịch sử'}).click();await other.locator('input[type=file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:backup});await expect(other.locator('.ebook-hero')).toContainText('Mục 3/826');await expect(other.locator('.ebook-history li')).toHaveCount(2);
 await other.locator('input[type=file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:backup});await expect(other.locator('.ebook-history li')).toHaveCount(2);
 await other.locator('input[type=file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"format":"wrong"}')});await expect(other.getByRole('status')).toContainText('Không phải bản sao');await expect(other.locator('.ebook-hero')).toContainText('Mục 3/826');await context.close();
});
test('ebook flashcards, writing, matching and mobile offline resume use only learned vocabulary',async({page,context})=>{
 await study(page,2);await page.getByRole('tab',{name:'Ôn tập & trò chơi'}).click();
 await page.getByRole('button',{name:/Ghép cặp trí nhớ/}).click();for(const w of book.words.slice(0,2)){await page.locator('.ebook-pairs>div').first().getByRole('button',{name:w.word,exact:true}).click();await page.locator('.ebook-pairs>div').last().getByRole('button',{name:w.meaning,exact:true}).click();}await expect(page.getByText('Đã lưu lượt ôn trên máy')).toBeVisible();await page.getByRole('button',{name:'Về e-book A'}).click();
 await page.getByRole('button',{name:/Viết nghĩa tiếng Việt/}).click();await page.getByLabel('Nghĩa tiếng Việt bạn nhớ').fill('Một cách diễn đạt của riêng tôi');await page.getByRole('button',{name:'Đối chiếu đáp án'}).click();await expect(page.getByText(/Cách diễn đạt tương đương/)).toBeVisible();await page.getByRole('button',{name:'Chưa nhớ',exact:true}).click();await page.getByRole('button',{name:'Đóng',exact:true}).click();
 await page.getByRole('button',{name:/Lật thẻ ghi nhớ/}).click();await expect(page.getByRole('button',{name:'Nhớ rồi',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Lật thẻ · Xem đáp án'}).click();await page.getByRole('button',{name:'Nhớ rồi',exact:true}).click();await page.getByRole('button',{name:'Đóng',exact:true}).click();
 for(const width of [320,390,768,1024,1440,1920]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Tiếp tục học theo thứ tự',exact:true}).click();await page.getByRole('button',{name:'Lật thẻ · Xem nghĩa và ví dụ'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Đóng',exact:true}).click();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(r=>navigator.serviceWorker.addEventListener('controllerchange',r,{once:true}));});await context.setOffline(true);await page.reload();await expect(page.locator('.ebook-hero')).toContainText('Mục 3/826');await page.getByRole('button',{name:'Tiếp tục học theo thứ tự',exact:true}).click();await page.getByRole('button',{name:'Lật thẻ · Xem nghĩa và ví dụ'}).click();await page.getByRole('button',{name:'Đã học · Lưu và tiếp tục'}).click();await expect(page.getByRole('dialog')).toHaveAttribute('aria-label','E-book A · Mục 4/826');await context.setOffline(false);
});
