"""Build 3,000 distinct words from open dictionaries; no generated IPA."""
import json,re,sqlite3,hashlib,sys
from pathlib import Path
sys.stdout.reconfigure(encoding='utf-8')
root=Path(__file__).resolve().parents[1]; source=root/'data-source'
def ipa_map(file):
 out={}
 for line in file.read_text(encoding='utf-8').splitlines():
  parts=line.split('\t')
  if len(parts)==2:
   first=re.search(r'/[^/]+/',parts[1])
   if first:out[parts[0]]=first.group(0)
 return out
uk=ipa_map(source/'en_UK.txt');us=ipa_map(source/'en_US.txt')
# Verified directly against the English Wiktionary pronunciation sections.
ipa_supplement={'sustainable':('/səˈsteɪnəbəl/','/səˈsteɪnəbəl/'),'biodiversity':('/ˌbaɪə(ʊ)daɪˈvɜːsɪti/','/ˌbaɪoʊdəˈvɚsəti/'),'misinformation':('/ˌmɪs.ɪn.fəˈmeɪ.ʃən/','/ˌmɪs.ɪn.fɚˈmeɪ.ʃən/')}
for w,(a,b) in ipa_supplement.items():uk[w]=a;us[w]=b
TOPICS=[
('education','Giáo dục','GraduationCap','Học tập, trường học và kỹ năng','academic academy education school university student teacher curriculum scholarship tuition literacy qualification lecture assignment assessment examination knowledge learning graduate degree diploma research study classroom lesson library pupil homework textbook training skill ability intellectual compulsory discipline achievement campus tutorial attendance instruction seminar professor faculty educational pedagogy motivation talent certificate revision exam subject'),
('environment','Môi trường','Leaf','Thiên nhiên và phát triển bền vững','sustainable sustainability environment environmental pollution climate biodiversity conservation renewable ecosystem emission emissions habitat deforestation drought flood endangered species recycling recycle waste carbon fossil energy wildlife nature forest ocean river soil atmosphere global warming ecological greenhouse extinction protect preserve plastic solar wind resource contamination degradation wilderness green organic oxygen vegetation rainfall temperature weather coastal glacier'),
('technology','Công nghệ','Cpu','Thế giới số và sự đổi mới','technology innovation artificial intelligence automation algorithm digital device internet software hardware network computer privacy security data database electronic smartphone mobile application virtual robot robotics programming scientific development modern technical access online satellite communication wireless computing engineering invention innovative equipment information system screen keyboard cable sensor signal machine machinery website browser password storage'),
('health','Sức khỏe','HeartPulse','Y tế, thể chất và tinh thần','health healthy healthcare medical medicine disease treatment prevention nutrition obesity exercise diagnosis therapy immune mental psychological stress wellbeing hospital doctor nurse patient surgery infection vaccine vaccination symptom recovery fitness diet vitamin protein calorie chronic diabetes cancer illness prescription antibiotic rehabilitation hygiene epidemic pandemic depression anxiety sleep pharmacy disability mortality ambulance emergency clinic blood heart lung breathing physical wellness'),
('society','Xã hội','Users','Cộng đồng, bình đẳng và dân số','society social community inequality equality diversity population demographic migration immigration integration discrimination poverty welfare urban rural generation elderly tradition cultural culture identity solidarity minority majority inclusion inclusive citizenship citizen public individual collective socialization age gender ethnic religion religious belief secular justice fair fairness rights humanity charitable charity voluntary volunteer homelessness homeless wealthy rich poor humanitarian'),
('work','Công việc','Briefcase','Nghề nghiệp và môi trường làm việc','employment unemployment occupation profession career employer employee workforce salary wage promotion productivity recruitment interview workplace labor labour job work office colleague management manager leadership teamwork resume experience expertise professional retire retirement pension overtime shift flexible flexibility income earn worker duty responsibility responsible task contract bonus incentive performance competent competence vacancy applicant satisfaction benefit efficient efficiency business company enterprise organization organisation'),
('economy','Kinh tế','TrendingUp','Kinh doanh, tài chính và thương mại','economy economic economics inflation investment revenue expenditure growth recession consumer consumption production supply demand market finance financial budget profit loss trade export import currency monetary fiscal tax taxation capital entrepreneur entrepreneurship industry industrial agriculture retail purchase purchasing cost price expense expensive cheap affordable affordability savings banking bank debt credit interest loan wealth prosperity distribution transaction account payment cash money fund funding invest sale seller buyer stock share dividend insurance commercial commerce manufacturer manufacturing goods'),
('government','Chính sách','Landmark','Nhà nước và quyền công dân','government governance policy regulation legislation democracy democratic authority administration political politics parliament election electoral voter vote president minister ministry council municipal mayor state national federal constitution law legal enforce enforcement subsidy subsidies reform institution corruption transparent transparency accountability bureaucracy civil freedom liberty campaign politician representative senator diplomatic diplomacy foreign domestic international opposition debate decision judiciary judicial court judge'),
('travel','Du lịch & giao thông','Plane','Đi lại, trải nghiệm và kết nối','travel tourism tourist destination accommodation itinerary journey adventure exploration heritage landmark hospitality visitor hotel hostel resort guide luggage passport visa flight airport abroad overseas trip tour vacation holiday sightseeing souvenir attraction museum gallery explore visit scenic landscape route transportation transport commute congestion infrastructure vehicle railway train traffic pedestrian bicycle bus car taxi road highway street bridge tunnel ferry port station ticket fare departure arrival delay terminal cruise ship passenger driver driving parking mobility accessible accessibility'),
('science','Khoa học','FlaskConical','Nghiên cứu và khám phá','science research experiment experimental laboratory hypothesis theory evidence observation analysis analyse analyze discovery discover phenomenon phenomena biology chemistry physics astronomy molecule molecular atom atomic evolution genetics genetic innovation invention measurement measure quantity quantitative qualitative methodology method result investigation investigate accurate accuracy precise precision reliable reliability validity valid conclusion sample sampling survey scientist objective objectivity subjective evaluate evaluation variable statistics statistical correlation causation calculation calculate formula equation probability microscope telescope gravity radiation chemical substance material element compound reaction'),
('arts','Văn hóa & nghệ thuật','Palette','Sáng tạo, nghệ thuật và bản sắc','art arts artistic artist creativity creative music musical musician literature literary poetry poem poet novel novelist fiction drama theatre theater performance perform painting paint painter sculpture sculptor architecture architect exhibition festival celebration cinema film movie actor actress audience concert instrument photography photograph photographer visual aesthetic design designer craft contemporary classical style masterpiece portrait opera ballet dance dancing historic historical history civilisation civilization language linguistic entertainment entertain event'),
('food','Ẩm thực','Utensils','Thực phẩm, dinh dưỡng và nông nghiệp','food nutritious ingredient cuisine cooking cook meal breakfast lunch dinner restaurant cafe coffee tea water bread rice meat vegetable vegetables fruit fruits grain dairy milk cheese yogurt fish seafood chicken beef pork egg eggs salt sugar oil butter carbohydrates mineral fibre fiber fresh frozen processed farming farm farmer crop crops harvest irrigation livestock poultry cattle vegetarian vegan appetite hunger hungry thirsty taste tasty delicious flavour flavor recipe kitchen oven stove pan bake boil fry roast grill steam spicy sweet bitter sour seasoning'),
('home','Nhà ở & đô thị','House','Không gian sống và phát triển đô thị','housing house home apartment neighbourhood neighborhood city town village suburb suburban metropolitan residential residence resident construction building rental rent property estate landlord tenant ownership owner mortgage renovation interior exterior furniture bedroom bathroom living garden balcony roof ceiling floor wall window door dwelling household shelter settlement utility utilities electricity heating spacious crowded density planning builder cleanliness clean comfortable comfort convenience convenient insulation'),
('media','Truyền thông','Newspaper','Tin tức, mạng xã hội và quảng cáo','media journalism journalist newspaper news information communication communicate broadcast broadcasting television radio podcast advertisement advertising marketing publicity campaign influence influential misinformation disinformation censorship speech press publication publish publisher article headline editor editorial report reporter reporting platform content creator follower fake bias biased impartial coverage source credible credibility subscribe subscription subscriber magazine video viral celebrity fame famous trend trending popular popularity brand branding awareness opinion discussion review critical criticism'),
('sports','Thể thao','Trophy','Vận động, thi đấu và sở thích','sport sports athlete athletic athletics competition competitive compete tournament championship champion coach endurance strength stamina team opponent rival victory defeat win lose goal score scoring match game player field stadium swimming football soccer tennis basketball volleyball running cycling hiking climbing ski skiing golf badminton cricket baseball rugby race racing marathon medal gold silver bronze referee spectator supporter club membership hobby hobbies leisure recreation recreational outdoor indoors dedication participation participant amateur equipment practice activity'),
('relationships','Con người & cảm xúc','Smile','Giao tiếp, tính cách và quan hệ','relationship relationships friendship friend family parent parents mother father brother sister child children husband wife marriage married wedding single divorce divorced relative relatives acquaintance companion partner partnership support trust trustworthy loyalty loyal respect respectful empathy sympathetic sympathy affection love happiness happy sad sadness anger angry anxious confidence confident patience personality character attitude behavior behaviour generous generosity kind kindness honest honesty ambitious ambition optimistic optimism pessimistic pessimism introvert extrovert sociable independence independent dependent emotional emotion feeling feelings curiosity curious caring helpful understanding understand worry fear afraid joy enjoyable'),
('academic','Ngôn ngữ học thuật','BookOpen','Lập luận, phân tích và trình bày ý tưởng','assess assume assumption approach concept conceptual constitute context contextual consistent consistency considerable crucial significant significance indicate indication interpret interpretation derive demonstrate demonstration establish estimate estimation evident factor function functional identify identification impact implication imply involve issue maintain major minor occur occurrence percent percentage period principle process require requirement respond response role section sector specific structure structured theoretical vary variation relevant relevance sufficient insufficient substantial substantially contribute contribution consequence consequently benefit beneficial challenge challenging solution resolve argument assert assertion perspective aspect alternative potential furthermore moreover nevertheless therefore whereas although despite however hence thus accordingly overall conclude summarize summary illustrate illustration emphasize emphasis distinguish distinction implement implementation strategy strategic fundamental essential complex complexity comprehensive coherent coherence criterion criteria instance proportion distribution'),
('nature','Thiên nhiên & động vật','TreePine','Địa lý, động vật và cảnh quan','animal animals mammal mammalian bird birds insect insects reptile reptiles amphibian marine aquatic terrestrial predator prey carnivore herbivore omnivore breed breeding migrate adaptation adapt ecology evolve survival survive extinct jungle rainforest desert mountain valley hill island beach coast sea lake stream waterfall volcano volcanic earthquake seismic geology geological geography geographical continent hemisphere latitude longitude equator tropical temperate polar arctic antarctic cloud rain snow storm sunlight sunshine thunder lightning rainbow grass flower tree plant leaf root branch seed sand rock stone pet'),
('law','Pháp luật & an toàn','ShieldCheck','Công lý, an ninh và an toàn','crime criminal illegal lawful court judge jury trial witness testimony suspect suspicion innocent innocence guilty guilt verdict sentence sentencing punishment penalty prison imprisonment jail police officer detective arrest detention charge prosecution prosecute prosecutor defense defence lawyer attorney solicitor barrister violation violate offence offense fraud theft robbery burglary violence violent safety safe secure dangerous danger hazard risk risky accident incident victim protection deterrent deter consent surveillance bribe bribery'),
('global','Thế giới & tương lai','Globe','Quan hệ quốc tế và sự thay đổi','global globalization globalisation cooperation collaboration nation country countries border boundary emigration immigrant refugee asylum aid assistance relief developing developed trading corporation integrate interaction interconnected connection multinational conflict peace peaceful war negotiation negotiate treaty agreement alliance allied united union sovereignty sovereign regional region worldwide universal opportunity future progress progressive change'),
('daily','Đời sống hằng ngày','Coffee','Từ nền tảng để giao tiếp mỗi ngày','daily day night morning afternoon evening today tomorrow yesterday week month year time hour minute second people person man woman boy girl adult name address phone number email birthday life live eat drink wake wash brush buy sell shop shopping supermarket store card bill bag clothes shirt dress trousers shoes coat hat umbrella hot cold warm cool rainy sunny cloudy windy appointment schedule plan invitation invite meeting date walk run sit stand speak talk say tell ask answer question call text message help thank thanks sorry please excuse greet greeting hello goodbye welcome good bad great nice beautiful wonderful small big large little long short high low new old young important interesting easy difficult simple possible ready busy free available early late tired fast slow careful different same open close begin finish start stop go come bring take give get make do have want need like prefer think know remember forget find lose use learn read write listen hear watch see look')
]
topic_for={}
for id,name,icon,desc,seeds in TOPICS:
 for word in seeds.split():topic_for.setdefault(word,id)
# Original contextual examples and concise meaning corrections for the featured IELTS lessons.
# These are editorial content, not a claim of external human certification.
OVERRIDE_TEXT="""sustainable|bền vững|adjective|Investing in renewable energy is essential for sustainable development.|Đầu tư vào năng lượng tái tạo là điều thiết yếu cho phát triển bền vững.|sustainable development
education|giáo dục|noun|Access to quality education can reduce social inequality.|Tiếp cận giáo dục chất lượng có thể giảm bất bình đẳng xã hội.|quality education
environment|môi trường|noun|Governments should protect the environment for future generations.|Chính phủ nên bảo vệ môi trường cho các thế hệ tương lai.|protect the environment
research|nghiên cứu|noun|Recent research suggests that regular exercise improves mental health.|Nghiên cứu gần đây cho thấy tập thể dục đều đặn cải thiện sức khỏe tinh thần.|conduct research
ability|khả năng|noun|The ability to communicate clearly is valuable in any career.|Khả năng giao tiếp rõ ràng rất có giá trị trong bất kỳ nghề nghiệp nào.|the ability to
abandon|từ bỏ; bỏ rơi|verb|The council decided to abandon the expensive construction project.|Hội đồng quyết định từ bỏ dự án xây dựng tốn kém.|abandon a plan
significant|đáng kể; có ý nghĩa|adjective|Public transport can make a significant contribution to cleaner cities.|Giao thông công cộng có thể đóng góp đáng kể cho các thành phố sạch hơn.|a significant contribution
biodiversity|đa dạng sinh học|noun|Protecting forests helps preserve biodiversity for future generations.|Bảo vệ rừng giúp gìn giữ đa dạng sinh học cho các thế hệ tương lai.|preserve biodiversity
curriculum|chương trình học|noun|The school curriculum includes science and environmental education.|Chương trình học của trường bao gồm khoa học và giáo dục môi trường.|school curriculum
innovation|sự đổi mới; sáng kiến|noun|Technological innovation can improve access to healthcare.|Đổi mới công nghệ có thể cải thiện khả năng tiếp cận dịch vụ y tế.|technological innovation
inequality|sự bất bình đẳng|noun|Affordable housing can help reduce inequality in large cities.|Nhà ở giá phải chăng có thể giúp giảm bất bình đẳng ở các thành phố lớn.|reduce inequality
conservation|sự bảo tồn|noun|Wildlife conservation requires cooperation between local communities.|Bảo tồn động vật hoang dã đòi hỏi sự hợp tác giữa các cộng đồng địa phương.|wildlife conservation
renewable|có thể tái tạo|adjective|Solar and wind power are renewable sources of energy.|Năng lượng mặt trời và gió là những nguồn năng lượng tái tạo.|renewable energy
pollution|sự ô nhiễm|noun|Air pollution is a major concern in many urban areas.|Ô nhiễm không khí là mối lo lớn ở nhiều khu vực đô thị.|air pollution
climate|khí hậu|noun|Changes in the climate affect agriculture and water supplies.|Những thay đổi về khí hậu ảnh hưởng đến nông nghiệp và nguồn cung nước.|climate change
emission|sự phát thải; lượng phát thải|noun|The emission of greenhouse gases contributes to global warming.|Sự phát thải khí nhà kính góp phần gây ra sự nóng lên toàn cầu.|the emission of greenhouse gases
habitat|môi trường sống|noun|Urban expansion can destroy the natural habitat of many species.|Sự mở rộng đô thị có thể phá hủy môi trường sống tự nhiên của nhiều loài.|natural habitat
deforestation|nạn phá rừng|noun|Deforestation threatens wildlife and increases soil erosion.|Nạn phá rừng đe dọa động vật hoang dã và làm tăng xói mòn đất.|prevent deforestation
scholarship|học bổng|noun|She received a scholarship to study engineering abroad.|Cô ấy nhận được học bổng để học ngành kỹ thuật ở nước ngoài.|receive a scholarship
tuition|học phí; việc giảng dạy|noun|High tuition fees can prevent students from attending university.|Học phí cao có thể ngăn sinh viên theo học đại học.|tuition fees
literacy|khả năng đọc và viết|noun|Improving literacy gives people access to more job opportunities.|Cải thiện khả năng đọc và viết giúp mọi người tiếp cận nhiều cơ hội việc làm hơn.|improve literacy
qualification|bằng cấp; trình độ chuyên môn|noun|A professional qualification can improve your career prospects.|Một bằng cấp chuyên môn có thể cải thiện triển vọng nghề nghiệp của bạn.|professional qualification
assessment|sự đánh giá|noun|Regular assessment helps teachers identify gaps in learning.|Đánh giá thường xuyên giúp giáo viên xác định những lỗ hổng trong việc học.|regular assessment
automation|sự tự động hóa|noun|Automation may replace some jobs while creating new opportunities.|Tự động hóa có thể thay thế một số công việc đồng thời tạo ra những cơ hội mới.|industrial automation
privacy|quyền riêng tư; sự riêng tư|noun|Online services should respect the privacy of their users.|Các dịch vụ trực tuyến nên tôn trọng quyền riêng tư của người dùng.|respect privacy
nutrition|dinh dưỡng|noun|Good nutrition is essential for healthy growth in children.|Dinh dưỡng tốt là điều thiết yếu cho sự phát triển khỏe mạnh ở trẻ em.|good nutrition
obesity|tình trạng béo phì|noun|Regular physical activity can help prevent obesity.|Hoạt động thể chất thường xuyên có thể giúp ngăn ngừa béo phì.|prevent obesity
prevention|sự phòng ngừa|noun|Disease prevention is often less costly than treatment.|Phòng bệnh thường ít tốn kém hơn điều trị.|disease prevention
migration|sự di cư|noun|Economic opportunities are a major cause of migration.|Cơ hội kinh tế là một nguyên nhân chính của sự di cư.|economic migration
diversity|sự đa dạng|noun|Cultural diversity can enrich the life of a community.|Sự đa dạng văn hóa có thể làm phong phú đời sống của một cộng đồng.|cultural diversity
employment|việc làm; sự tuyển dụng|noun|Education can improve access to stable employment.|Giáo dục có thể cải thiện khả năng tiếp cận việc làm ổn định.|stable employment
productivity|năng suất|noun|Flexible working hours may increase employee productivity.|Giờ làm việc linh hoạt có thể tăng năng suất của nhân viên.|increase productivity
inflation|lạm phát|noun|High inflation reduces the purchasing power of households.|Lạm phát cao làm giảm sức mua của các hộ gia đình.|high inflation
investment|sự đầu tư; khoản đầu tư|noun|Investment in public transport can reduce traffic congestion.|Đầu tư vào giao thông công cộng có thể giảm ùn tắc giao thông.|investment in
revenue|doanh thu; nguồn thu|noun|Tourism provides an important source of revenue for the region.|Du lịch cung cấp một nguồn thu quan trọng cho khu vực.|a source of revenue
consumption|sự tiêu thụ|noun|Reducing energy consumption can lower household expenses.|Giảm tiêu thụ năng lượng có thể giảm chi phí sinh hoạt của hộ gia đình.|energy consumption
legislation|luật pháp; việc ban hành luật|noun|New legislation aims to protect workers from discrimination.|Luật mới nhằm bảo vệ người lao động khỏi sự phân biệt đối xử.|introduce legislation
infrastructure|cơ sở hạ tầng|noun|Reliable infrastructure is essential for economic development.|Cơ sở hạ tầng đáng tin cậy là điều thiết yếu cho phát triển kinh tế.|transport infrastructure
accommodation|chỗ ở|noun|Students often find it difficult to afford accommodation near campus.|Sinh viên thường khó có đủ tiền trả cho chỗ ở gần trường.|affordable accommodation
congestion|sự ùn tắc|noun|Better public transport can reduce traffic congestion in cities.|Giao thông công cộng tốt hơn có thể giảm ùn tắc giao thông trong các thành phố.|traffic congestion
hypothesis|giả thuyết|noun|The researchers tested their hypothesis through a series of experiments.|Các nhà nghiên cứu kiểm chứng giả thuyết qua một loạt thí nghiệm.|test a hypothesis
evidence|bằng chứng|noun|There is strong evidence that exercise benefits mental health.|Có bằng chứng thuyết phục rằng tập thể dục có lợi cho sức khỏe tinh thần.|strong evidence
heritage|di sản|noun|Historic buildings are an important part of our cultural heritage.|Các tòa nhà lịch sử là một phần quan trọng của di sản văn hóa.|cultural heritage
misinformation|thông tin sai lệch|noun|Misinformation can spread quickly on social media platforms.|Thông tin sai lệch có thể lan truyền nhanh trên các nền tảng mạng xã hội.|spread misinformation
analyze|phân tích|verb|Researchers analyze the data before drawing conclusions.|Các nhà nghiên cứu phân tích dữ liệu trước khi rút ra kết luận.|analyze data
approach|cách tiếp cận; phương pháp|noun|A balanced approach can help address complex social problems.|Cách tiếp cận cân bằng có thể giúp giải quyết các vấn đề xã hội phức tạp.|a balanced approach
consequence|hậu quả; hệ quả|noun|One consequence of urban growth is increased demand for housing.|Một hệ quả của tăng trưởng đô thị là nhu cầu nhà ở gia tăng.|a consequence of
contribute|đóng góp; góp phần|verb|Public libraries contribute to lifelong learning in the community.|Thư viện công cộng góp phần vào việc học suốt đời trong cộng đồng.|contribute to
significance|tầm quan trọng; ý nghĩa|noun|The study highlights the significance of early education.|Nghiên cứu làm nổi bật tầm quan trọng của giáo dục sớm.|the significance of
beneficial|có lợi|adjective|Regular exercise is beneficial for both physical and mental health.|Tập thể dục thường xuyên có lợi cho cả sức khỏe thể chất lẫn tinh thần.|beneficial for
considerable|đáng kể; lớn|adjective|The city has made considerable progress in reducing waste.|Thành phố đã đạt tiến bộ đáng kể trong việc giảm chất thải.|considerable progress
crucial|rất quan trọng; mang tính quyết định|adjective|Access to clean water is crucial for public health.|Tiếp cận nước sạch rất quan trọng đối với sức khỏe cộng đồng.|crucial for
implement|thực hiện; triển khai|verb|Schools can implement policies that encourage healthy eating.|Các trường có thể triển khai chính sách khuyến khích ăn uống lành mạnh.|implement a policy
perspective|góc nhìn; quan điểm|noun|Travel can help people see the world from a different perspective.|Du lịch có thể giúp mọi người nhìn thế giới từ một góc nhìn khác.|a different perspective
relevant|có liên quan; phù hợp|adjective|Students should develop skills that are relevant to the workplace.|Sinh viên nên phát triển kỹ năng phù hợp với môi trường làm việc.|relevant to
substantial|đáng kể; lớn|adjective|The new railway requires substantial investment from the government.|Tuyến đường sắt mới đòi hỏi khoản đầu tư lớn từ chính phủ.|substantial investment
discrimination|sự phân biệt đối xử|noun|Clear policies can help prevent discrimination at work.|Chính sách rõ ràng có thể giúp ngăn ngừa sự phân biệt đối xử tại nơi làm việc.|prevent discrimination
accessible|có thể tiếp cận; dễ tiếp cận|adjective|Public buildings should be accessible to people with disabilities.|Các tòa nhà công cộng nên dễ tiếp cận đối với người khuyết tật.|accessible to
affordable|có giá phải chăng; có thể chi trả|adjective|Affordable housing is a priority for many local governments.|Nhà ở giá phải chăng là ưu tiên của nhiều chính quyền địa phương.|affordable housing
advantage|lợi thế; ưu điểm|noun|One advantage of online learning is greater flexibility.|Một ưu điểm của học trực tuyến là sự linh hoạt cao hơn.|an advantage of
disadvantage|bất lợi; nhược điểm|noun|A major disadvantage of living in a large city is traffic noise.|Một nhược điểm lớn của việc sống ở thành phố lớn là tiếng ồn giao thông.|a major disadvantage
challenge|thách thức|noun|Climate change is a major challenge for many countries.|Biến đổi khí hậu là một thách thức lớn đối với nhiều quốc gia.|a major challenge"""
overrides={line.split('|')[0]:line.split('|')[1:] for line in OVERRIDE_TEXT.splitlines()}
conn=sqlite3.connect(source/'dictionary.db')
freq=(source/'frequency.txt').read_text().splitlines();rank={w:i for i,w in enumerate(freq)}
candidate=list(dict.fromkeys(list(overrides)+list(topic_for)+freq))
bad=re.compile(r'^(A|An|The) \w+ (helped the team|was important|is important)|She saw the|He saw the|We discussed the word|This is a|They mentioned|It is a',re.I)
pos_names={'N':'noun','V':'verb','A':'adjective','D':'adverb','noun':'noun','verb':'verb','adjective':'adjective','adverb':'adverb'}
entries=[];excluded=[]
for word in candidate:
 if not re.fullmatch('[a-z][a-z-]{1,24}',word) or word not in uk or word not in us:continue
 rows=conn.execute('SELECT d.definition,d.pos,wd.example FROM words w JOIN word_definitions wd ON w.id=wd.word_id JOIN definitions d ON d.id=wd.definition_id WHERE w.word=? AND d.definition_lang="vi"',(word,)).fetchall()
 valid=[]
 for row_index,(meaning,pos,example) in enumerate(rows):
  if not example or len(example.split())<6 or len(example)>230 or not re.search(r'\b'+re.escape(word)+r'\b',example,re.I):continue
  if bad.search(example) or not meaning or not meaning.strip().strip('.') or len(meaning)>160 or re.search(r'\([^)]*(hóa học|sinh vật|y học|địa lý|kỹ thuật|quân sự|nhiếp ảnh|toán học)',meaning,re.I):continue
  if pos not in pos_names:continue
  score=(100 if pos in ['noun','verb','adjective','adverb'] else 0)-row_index
  valid.append((score,meaning.strip().rstrip('.'),pos_names[pos],example.strip()))
 if word in overrides:
  meaning,pos,example,vi,collocation=overrides[word];editorial=True
 elif valid:
  _,meaning,pos,example=max(valid,key=lambda x:x[0]);vi=None;collocation=None;editorial=False
 else:excluded.append(word);continue
 topic=topic_for.get(word,'daily')
 entries.append({'id':word,'word':word,'ipaUK':uk[word],'ipaUS':us[word],'meaning':meaning,'pos':pos,'example':example,'exampleVi':vi,'collocation':collocation,'topic':topic,'editorial':editorial,'source':'editorial' if editorial else 'skypedia-minhqnd','exampleSource':'original' if editorial else 'upstream-generated','rank':rank.get(word,12000)})
entries.sort(key=lambda e:(0 if e['editorial'] else 1 if e['word'] in topic_for else 2,e['rank']))
if len(entries)<3000:raise SystemExit(f'Only {len(entries)} eligible headwords, need 3,000. No padding permitted.')
entries=entries[:3000]
quality_fixes={}
for line in (root/'scripts/quality-fixes.tsv').read_text(encoding='utf-8').splitlines():
 word,meaning,pos,example,vi,collocation=line.split('|')
 quality_fixes[word]=(meaning,pos,example,vi,collocation)
for entry in entries:
 if entry['word'] in quality_fixes:
  meaning,pos,example,vi,collocation=quality_fixes[entry['word']]
  entry.update(meaning=meaning,pos=pos,example=example,exampleVi=vi,collocation=collocation,editorial=True,source='editorial',exampleSource='original')
for e in entries:e.pop('rank')
topics=[{'id':id,'name':name,'icon':icon,'description':desc,'count':sum(e['topic']==id for e in entries)} for id,name,icon,desc,seeds in TOPICS]
(root/'public/vocabulary.json').write_text(json.dumps(entries,ensure_ascii=False,separators=(',',':')),encoding='utf-8')
(root/'src/topics.json').write_text(json.dumps(topics,ensure_ascii=False,indent=2),encoding='utf-8')
report={'total':len(entries),'unique':len(set(e['word'] for e in entries)),'ipaUK':len(entries),'ipaUS':len(entries),'examples':len(entries),'editorial':sum(e['editorial'] for e in entries),'imported':sum(not e['editorial'] for e in entries),'humanReviewed':False,'excluded':len(excluded),'sha256':hashlib.sha256((root/'public/vocabulary.json').read_bytes()).hexdigest(),'sourceHashes':{f:hashlib.sha256((source/f).read_bytes()).hexdigest() for f in ['dictionary.db','en_UK.txt','en_US.txt','frequency.txt']},'topics':topics}
(root/'public/content-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({k:v for k,v in report.items() if k not in ['topics','sourceHashes']},ensure_ascii=False));print([(t['id'],t['count']) for t in topics])
