import React,{useState,useEffect,useMemo,useRef} from 'react';
import {Crown,Compass,Gamepad2,Layers,BookOpen,RotateCcw,Heart,Mic,Settings,Flame,Star,Coins,ArrowRight,ChevronRight,Volume2,X,Target,Search,Leaf,Download,Upload,Bell,Trophy,Menu,HelpCircle,WifiOff,ExternalLink,Flag,Swords,Check,TreePine} from 'lucide-react';
import topics from './topics.json';
import Ebook from './Ebook';
import {load,STORAGE_KEY,localDay,dueWords,grade,streak,sessionWords,validateSave} from './learning';
import {speak,stopSpeech} from './speech';
import {Session,Modal,WordDetail,RatingButtons,Pronunciation} from './Session';
import {GameTile,TopicCard,TopicSelect,WordCard,About,Achievements,gameTypes} from './components';
const nav=[['home','Khám phá',Compass],['ebook','E-book A',BookOpen],['games','Học qua game',Gamepad2],['flashcards','Flashcards',Layers],['vocabulary','Kho từ vựng',BookOpen],['review','Ôn tập hôm nay',RotateCcw],['favorites','Từ yêu thích',Heart],['pronunciation','Luyện phát âm',Mic],['settings','Cài đặt',Settings]];
const topicName=id=>topics.find(t=>t.id===id)?.name||'Từ vựng';
export default function App(){
 const [words,setWords]=useState([]),[error,setError]=useState(''),[state,setState]=useState(load),[page,setPage]=useState(()=>location.hash==='#ebook-a'?'ebook':'home'),[topic,setTopic]=useState('all'),[query,setQuery]=useState(''),[visible,setVisible]=useState(24),[notice,setNotice]=useState(''),[menu,setMenu]=useState(false),[session,setSession]=useState(null),[selected,setSelected]=useState(null),[offline,setOffline]=useState(!navigator.onLine),[install,setInstall]=useState(null),[tick,setTick]=useState(0);
 const fileRef=useRef(),toastTimer=useRef(),reminded=useRef(''),wordRefs=useMemo(()=>new Map(words.map(w=>[w.id,w])),[words]);
 function notify(text){setNotice(text);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setNotice(''),7000);}
 function save(fn){setState(old=>{const next=typeof fn==='function'?fn(old):fn;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}catch{setTimeout(()=>notify('Thiết bị không lưu được tiến độ. Hãy xuất bản sao trong Cài đặt.'),0);}return next;});}
 useEffect(()=>{let alive=true;fetch(import.meta.env.BASE_URL+'vocabulary.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(w=>{if(alive){if(w.length!==3000)throw Error();setWords(w);}}).catch(()=>{if(alive)setError('Chưa tải được kho từ vựng. Kiểm tra kết nối rồi tải lại.');});return()=>{alive=false;clearTimeout(toastTimer.current);};},[]);
 useEffect(()=>{const update=()=>setOffline(!navigator.onLine),offer=e=>{e.preventDefault();setInstall(e);};window.addEventListener('online',update);window.addEventListener('offline',update);window.addEventListener('beforeinstallprompt',offer);const t=setInterval(()=>setTick(x=>x+1),30000);window.speechSynthesis?.getVoices();return()=>{clearInterval(t);window.removeEventListener('online',update);window.removeEventListener('offline',update);window.removeEventListener('beforeinstallprompt',offer);};},[]);
 useEffect(()=>{if(!state.settings.notifications||session)return;const day=localDay(),now=new Date(),[h,m]=state.settings.reminder.split(':').map(Number);if(now.getHours()*60+now.getMinutes()<h*60+m||(state.days[day]||0)>=state.settings.goal||reminded.current===day)return;reminded.current=day;notify('Đến giờ học! Một lượt chơi 10 từ đang chờ bạn.');if(window.Notification?.permission==='granted')navigator.serviceWorker?.ready.then(r=>r.showNotification('Vua Tiếng Anh · Đến giờ học',{body:'Chơi một lượt, ôn vài từ và giữ nhịp học hôm nay.',icon:import.meta.env.BASE_URL+'icon-192.png',tag:'daily-study'})).catch(()=>{});},[tick,state.settings.notifications,session]);
 const due=useMemo(()=>dueWords(words,state),[words,state,tick]),learned=Object.keys(state.cards).length,mastered=Object.values(state.cards).filter(c=>c.interval>=21).length,today=state.days[localDay()]||0,currentStreak=streak(state),level=Math.floor(state.xp/200)+1;
 function go(p){history.replaceState(null,'',location.pathname+location.search+(p==='ebook'?'#ebook-a':''));setPage(p);setQuery('');setVisible(24);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});}
 function favorite(w){save(s=>({...s,favorites:s.favorites.includes(w.id)?s.favorites.filter(x=>x!==w.id):[...s.favorites,w.id]}));}
 function start(mode,opts={}){const deck=sessionWords(words,state,{topic,count:mode==='match'?5:10,...opts});if(!deck.length){notify(opts.review?'Bạn đã ôn xong những từ đến hạn. Chơi thêm để học từ mới!':'Chưa có từ trong nhóm này. Hãy chọn chủ đề khác hoặc thêm từ yêu thích.');return;}setSession({id:Date.now(),mode,deck,pool:words.filter(w=>topic==='all'||w.topic===topic),review:!!opts.review,stage:state.stage});}
 const dailyWord=words.find(w=>w.word==='sustainable')||words[0];
 const filtered=useMemo(()=>words.filter(w=>(topic==='all'||w.topic===topic)&&(page!=='favorites'||state.favorites.includes(w.id))&&(!query||w.word.includes(query.toLowerCase().trim())||w.meaning.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')))),[words,topic,page,state.favorites,query]);
 return <div className="app-shell"><a className="skip" href="#main">Đi đến nội dung</a>
 <aside className={'sidebar '+(menu?'shown':'')}><button className="brand" onClick={()=>go('home')}><span className="brand-symbol"><Crown size={25}/></span><span>Vua Tiếng Anh<small>PLAY. LEARN. GROW.</small></span></button><div className="sidebar-label">KHÔNG GIAN HỌC TẬP</div><nav aria-label="Điều hướng chính">{nav.map(([id,label,I])=><button key={id} className={page===id?'nav-item active':'nav-item'} onClick={()=>go(id)}><I size={20}/><span>{label}</span>{id==='review'&&due.length>0&&<b>{due.length}</b>}{id==='games'&&<span className="tiny new">5</span>}</button>)}</nav><div className="sidebar-bottom"><div className="level-medal"><Star fill="currentColor" size={20}/></div><div><b>Nhà thám hiểm · Cấp {level}</b><small>{state.xp%200} / 200 XP lên cấp</small></div><progress value={state.xp%200} max="200"/><p>Mỗi lần nhớ đúng là một bước tiến.</p></div><button className="sidebar-link" onClick={()=>go('about')}><HelpCircle size={17}/>Nguồn dữ liệu & hướng dẫn</button></aside>
 {menu&&<button className="menu-scrim" aria-label="Đóng menu" onClick={()=>setMenu(false)}/>}
 <div className="main-shell"><header className="topbar"><div className="topbar-left"><button className="mobile-menu icon-button" aria-label="Mở menu" onClick={()=>setMenu(!menu)}><Menu/></button><span className="eyebrow">YOUR NEXT CHAPTER</span><span className="topbar-label">Hôm nay, mình học gì nhỉ?</span></div><div className="topbar-right">{offline&&<span className="offline"><WifiOff size={15}/>Ngoại tuyến</span>}<span className="streak"><Flame size={18} fill="currentColor"/>{currentStreak}<span className="hide-xs"> ngày</span></span><span className="coin-count"><Coins size={18}/>{state.coins}</span><button className="avatar" onClick={()=>go('settings')} aria-label="Cài đặt tài khoản"><Crown size={21}/></button></div></header>
 <main id="main" className="content">{error?<section className="empty"><WifiOff/><h2>{error}</h2><button className="primary" onClick={()=>location.reload()}>Thử tải lại</button></section>:!words.length?<section className="empty"><div className="spinner"/><h2>Đang mở kho từ vựng…</h2></section>:<>
 {page==='home'&&<><div className="page-heading"><div><p className="eyebrow accent">MỘT CHÚT MỖI NGÀY, MỘT BƯỚC TIẾN THẬT XA</p><h1>Chơi một chút.<br className="mobile-break"/> Nhớ thêm nhiều.</h1><p>Hành trình 3.000 từ tiếng Anh của bạn bắt đầu từ đây.</p></div><button className="soft-button desktop-only" onClick={()=>go('settings')}><Target size={17}/>Mục tiêu: {state.settings.goal} lượt/ngày</button></div>
 <button className="ebook-home-link" onClick={()=>go('ebook')}><BookOpen size={24}/><span><b>Học từ vựng qua e-book A</b><small>826 mục · 15 chủ đề · Lộ trình và bộ nhớ riêng trên máy</small></span><ArrowRight size={20}/></button><div className="stats-row"><Stat icon={BookOpen} color="purple" value={learned} label="Từ đã luyện" sub="trong 3.000 từ"/><Stat icon={RotateCcw} color="orange" value={due.length} label="Từ đến hạn ôn" sub="Nhớ lâu hơn mỗi ngày" onClick={()=>go('review')}/><Stat icon={Flame} color="pink" value={currentStreak} label="Ngày học liên tiếp" sub="Xây một thói quen tốt"/><Stat icon={Trophy} color="green" value={mastered} label="Từ vững trí nhớ" sub="Khoảng ôn từ 21 ngày"/></div>
 <div className="home-grid"><section className="quest-panel"><div className="quest-head"><span className="pill"><span className="live-dot"/>HÀNH TRÌNH TỪ VỰNG</span><span className="chapter">Ải {state.stage} · {topic==='all'?'Khám phá tiếng Anh':topicName(topic)}</span></div><div className="quest-copy"><h2>Mở khóa thế giới<br/>bằng từng từ mới.</h2><p>10 câu hỏi. Những khám phá mới.<br/>Và một phiên bản giỏi hơn của chính bạn.</p><button className="primary" onClick={()=>start('adventure')}>Bắt đầu phiêu lưu <ArrowRight size={18}/></button><div className="quest-note"><span><Swords size={15}/>Vượt ải</span><span><Star size={15}/>Kiếm XP</span><span><RotateCcw size={15}/>Ôn từ tự động</span></div></div><JourneyMap stage={state.stage}/><div className="quest-footer"><span><Flag size={17}/>Câu trả lời đúng giúp bạn tiến lên.</span><button onClick={()=>go('games')}>Xem tất cả game <ChevronRight size={16}/></button></div></section>
 <section className="daily-word"><div className="section-eyebrow"><span>TỪ VỰNG TRONG NGÀY</span><Leaf size={19}/></div><span className="word-topic">{topicName(dailyWord.topic)}</span><h2 lang="en">{dailyWord.word}</h2><div className="pronunciation-line"><span>{state.settings.accent==='en-GB'?dailyWord.ipaUK:dailyWord.ipaUS}</span><button className="audio-circle" aria-label={'Nghe '+dailyWord.word} onClick={()=>speak(dailyWord.word,state.settings,notify)}><Volume2 size={19}/></button></div><p className="word-meaning">{dailyWord.meaning}<small>tính từ</small></p><blockquote lang="en">{dailyWord.example}</blockquote><p className="translation">{dailyWord.exampleVi}</p><div className="word-actions"><button onClick={()=>favorite(dailyWord)} className={state.favorites.includes(dailyWord.id)?'favorited':''}><Heart size={17} fill={state.favorites.includes(dailyWord.id)?'currentColor':'none'}/>{state.favorites.includes(dailyWord.id)?'Đã yêu thích':'Lưu từ'}</button><button onClick={()=>setSelected(dailyWord)}>Học từ này <ArrowRight size={17}/></button></div></section></div>
 <div className="section-title"><div><h2>Học theo cách bạn thích</h2><p>Mỗi trò chơi là một cách để ghi nhớ.</p></div><button className="text-button" onClick={()=>go('games')}>Tất cả trò chơi <ArrowRight size={16}/></button></div><div className="quick-games">{gameTypes.slice(1,4).map(g=><GameTile key={g.id} game={g} start={()=>start(g.id)}/>)}</div>
 <div className="section-title"><div><h2>Một chủ đề, cả thế giới từ vựng</h2><p>Từ nền tảng đến cách diễn đạt học thuật cho IELTS.</p></div><button className="text-button" onClick={()=>go('vocabulary')}>21 chủ đề <ArrowRight size={16}/></button></div><div className="topic-preview">{topics.slice(0,6).map(t=><TopicCard key={t.id} t={t} learned={words.filter(w=>w.topic===t.id&&state.cards[w.id]).length} onClick={()=>{setTopic(t.id);go('vocabulary');}}/>)}</div>
 <section className="daily-goal"><div className="goal-icon"><Target/></div><div><h3>Đi đều, bạn sẽ đi xa.</h3><p>{today>=state.settings.goal?'Đã hoàn thành mục tiêu hôm nay. Hẹn gặp lại ngày mai!':'Bạn đã luyện '+today+'/'+state.settings.goal+' lượt hôm nay. Thêm một lượt chơi nhé?'}</p></div><progress max={state.settings.goal} value={Math.min(today,state.settings.goal)}/><button className="soft-button" onClick={()=>start('flashcards')}>Học tiếp <ArrowRight size={16}/></button></section></>}
 {page==='ebook'&&<Ebook settings={state.settings} notify={notify}/>}
 {page==='games'&&<><PageTitle eyebrow="PLAY YOUR WAY" title="Sân chơi từ vựng" description="Chơi thật vui, nhớ thật lâu. Mọi câu trả lời đều cập nhật lịch ôn của bạn."/><TopicSelect topic={topic} setTopic={setTopic}/><div className="game-grid">{gameTypes.map(g=><GameTile key={g.id} game={g} start={()=>start(g.id)}/>)}</div><section className="info-band"><Trophy/><div><h3>Cấp {level} · {state.xp} XP · {state.coins} xu</h3><p>Mỗi đáp án đúng: +10 XP, +3 xu. Hoàn thành ải với ít nhất 80% đúng để mở ải mới. Xu là điểm thưởng trong app.</p></div></section><Achievements state={state}/></>}
 {['vocabulary','favorites'].includes(page)&&<><PageTitle eyebrow={page==='favorites'?'YOUR PERSONAL COLLECTION':'THE WORD ATLAS'} title={page==='favorites'?'Những từ bạn yêu thích':'Kho 3.000 từ tiếng Anh'} description={page==='favorites'?'Lưu những từ hữu ích, luyện lại theo cách của bạn.':'21 chủ đề · Nghĩa tiếng Việt · IPA Anh–Anh & Anh–Mỹ · Ví dụ trong ngữ cảnh'}/><div className="library-toolbar"><label className="search-box"><Search size={19}/><input type="search" placeholder="Tìm từ hoặc nghĩa tiếng Việt…" value={query} onChange={e=>{setQuery(e.target.value);setVisible(24);}} aria-label="Tìm từ vựng"/></label><TopicSelect topic={topic} setTopic={v=>{setTopic(v);setVisible(24);}}/>{page==='favorites'&&<button className="primary compact" onClick={()=>start('flashcards',{favorites:true})}><Layers size={17}/>Luyện từ yêu thích</button>}</div><div className="library-count">{filtered.length.toLocaleString('vi')} từ <span>· Chạm vào thẻ để xem ví dụ và luyện nói</span></div>{!filtered.length?<section className="empty"><Heart/><h2>{page==='favorites'?'Chưa có từ yêu thích trong nhóm này':'Chưa tìm thấy từ phù hợp'}</h2><p>Thử chủ đề khác hoặc lưu từ bằng biểu tượng trái tim.</p><button className="soft-button" onClick={()=>{setTopic('all');go('vocabulary');}}>Khám phá kho từ</button></section>:<><div className="vocab-grid">{filtered.slice(0,visible).map(w=><WordCard key={w.id} word={w} state={state} favorite={()=>favorite(w)} listen={()=>speak(w.word,state.settings,notify)} detail={()=>setSelected(w)}/>)}</div>{filtered.length>visible&&<button className="load-more soft-button" onClick={()=>setVisible(v=>v+24)}>Xem thêm 24 từ <ChevronRight size={17}/></button>}</>}</>}
 {page==='flashcards'&&<><PageTitle eyebrow="LESS SCROLLING, MORE RECALLING" title="Lật thẻ. Bật trí nhớ." description="Tự nhớ trước khi xem đáp án. Chọn mức độ nhớ để app lên lịch ôn phù hợp."/><div className="flashcards-start"><div className="demo-card"><Layers size={29}/><span>THẺ TỪ VỰNG</span><strong lang="en">discovery</strong><em>/dɪˈskʌvəri/</em><span>Mỗi chiếc thẻ, một khám phá mới.</span></div><div><span className="pill light-pill">HỌC THEO NHỊP CỦA BẠN</span><h2>Nhìn một từ.<br/>Nhớ cả một ngữ cảnh.</h2><p>Nghe phát âm, đọc ví dụ, luyện nói và đánh giá mức độ nhớ. Những từ khó sẽ xuất hiện lại sớm hơn.</p><TopicSelect topic={topic} setTopic={setTopic}/><div className="button-row"><button className="primary" onClick={()=>start('flashcards')}>Học 10 thẻ <ArrowRight size={18}/></button><button className="soft-button" onClick={()=>start('flashcards',{review:true})}>Ôn từ đến hạn ({due.length})</button></div></div></div><div className="rating-guide">{[['again','Chưa nhớ','Ôn lại sau 10 phút'],['hard','Hơi khó','Tăng khoảng ôn chậm'],['good','Nhớ rồi','Tăng khoảng ôn dần'],['easy','Rất dễ','Giãn lịch ôn lâu hơn']].map(([k,t,d])=><div key={k} className={k}><b>{t}</b><small>{d}</small></div>)}</div></>}
 {page==='review'&&<><PageTitle eyebrow="A LITTLE RECALL GOES A LONG WAY" title="Ôn hôm nay, nhớ ngày mai." description="App lên lịch theo mức độ nhớ của từng từ. Từ sai cần ôn lại sau 10 phút."/><div className="review-banner"><div className="review-symbol"><RotateCcw size={36}/></div><div><h2>{due.length?due.length+' từ đang chờ bạn':'Bạn đã ôn xong các từ đến hạn'}</h2><p>{due.length?'Một lượt ôn ngắn giúp kiến thức ở lại lâu hơn.':'Học thêm từ mới hoặc xem lịch ôn tiếp theo bên dưới.'}</p></div><button className="primary" onClick={()=>due.length?start('flashcards',{review:true}):start('adventure')}>{due.length?'Bắt đầu ôn tập':'Khám phá từ mới'}<ArrowRight size={18}/></button></div>{due.length>0&&<div className="vocab-grid">{due.slice(0,12).map(w=><WordCard key={w.id} word={w} state={state} favorite={()=>favorite(w)} listen={()=>speak(w.word,state.settings,notify)} detail={()=>setSelected(w)}/>)}</div>}<section className="panel schedule-panel"><h2>Lịch ôn sắp tới</h2><div className="schedule-grid">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);const n=Object.values(state.cards).filter(c=>localDay(c.due)===localDay(d)).length;return <div key={i} className={i===0?'today':''}><span>{i===0?'Hôm nay':d.toLocaleDateString('vi',{weekday:'short'})}</span><strong>{n}</strong><small>{d.toLocaleDateString('vi',{day:'2-digit',month:'2-digit'})}</small></div>;})}</div><p className="muted">Lịch cập nhật sau mỗi lần bạn đánh giá thẻ hoặc trả lời câu hỏi.</p></section></>}
 {page==='pronunciation'&&<Pronunciation words={words} settings={state.settings} notify={notify}/>}
 {page==='settings'&&<><PageTitle eyebrow="MAKE IT YOURS" title="Góc học tập của bạn" description="Chọn giọng nghe, mục tiêu mỗi ngày và giữ an toàn cho tiến độ."/><div className="settings-grid"><section className="panel"><h2><Volume2/>Giọng đọc & nhịp học</h2><label>Giọng tiếng Anh<select value={state.settings.accent} onChange={e=>save(s=>({...s,settings:{...s.settings,accent:e.target.value}}))}><option value="en-GB">Anh–Anh · British English</option><option value="en-US">Anh–Mỹ · American English</option></select></label><label>Tốc độ nghe <span>{state.settings.rate.toFixed(2)}×</span><input type="range" min=".5" max="1.2" step=".05" value={state.settings.rate} onChange={e=>save(s=>({...s,settings:{...s.settings,rate:Number(e.target.value)}}))}/></label><button className="soft-button" onClick={()=>speak('Every small step brings you closer to your goal.',state.settings,notify)}><Volume2 size={18}/>Nghe thử giọng đọc</button><label>Mục tiêu luyện tập mỗi ngày<select value={state.settings.goal} onChange={e=>save(s=>({...s,settings:{...s.settings,goal:Number(e.target.value)}}))}>{[10,20,30,50].map(n=><option key={n} value={n}>{n} lượt đánh giá từ / ngày</option>)}</select></label><p className="muted">Giọng đọc phụ thuộc giọng tiếng Anh được cài trên thiết bị. IPA có thể khác nhau giữa các vùng.</p></section>
 <section className="panel"><h2><Bell/>Nhắc học mỗi ngày</h2><label>Giờ học của bạn<input type="time" value={state.settings.reminder} onChange={e=>save(s=>({...s,settings:{...s.settings,reminder:e.target.value}}))}/></label><button className="primary" onClick={async()=>{if(state.settings.notifications){save(s=>({...s,settings:{...s.settings,notifications:false}}));return;}if(window.Notification&&Notification.permission==='default'){try{await Notification.requestPermission();}catch{}}save(s=>({...s,settings:{...s.settings,notifications:true}}));notify('Đã bật nhắc khi app đang mở. Thêm lịch bên dưới để được nhắc cả khi đóng app.');}}><Bell size={17}/>{state.settings.notifications?'Tắt nhắc khi app mở':'Bật nhắc khi app mở'}</button><button className="soft-button" onClick={()=>calendar(state.settings.reminder)}><Download size={17}/>Thêm nhắc hằng ngày vào Lịch</button><p className="muted">Nhắc trong app hoạt động khi app đang mở. Tệp Lịch tạo sự kiện lặp hằng ngày với báo trước 5 phút; thông báo phụ thuộc ứng dụng Lịch của bạn.</p></section>
 <section className="panel"><h2><Download/>Tiến độ & bản sao</h2><p>Đã luyện {learned} từ · {state.xp} XP · {state.favorites.length} từ yêu thích.</p><p>Tiến độ lưu trên trình duyệt của thiết bị này. Xuất rồi nhập bản sao để chuyển sang thiết bị khác.</p><button className="primary" onClick={()=>download(JSON.stringify(state,null,2),'vua-tieng-anh-'+localDay()+'.json','application/json')}><Download size={17}/>Xuất toàn bộ tiến độ</button><button className="soft-button" onClick={()=>fileRef.current.click()}><Upload size={17}/>Nhập bản sao tiến độ</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>5000000)throw Error();const s=JSON.parse(await f.text());if(!validateSave(s)||Object.keys(s.cards).some(id=>!wordRefs.has(id))||s.favorites.some(id=>!wordRefs.has(id)))throw Error();save(s);notify('Đã nhập bản sao tiến độ.');}catch{notify('Bản sao không hợp lệ. Tiến độ hiện tại được giữ nguyên.');}}}/></section>
 <section className="panel"><h2><Gamepad2/>Học như một ứng dụng</h2><p>Cài lên màn hình chính. Kho từ, flashcards và game có thể học ngoại tuyến sau khi app tải và lưu xong.</p><button className="primary" onClick={async()=>{if(install){await install.prompt();setInstall(null);}else notify('iPhone/iPad: Safari → Chia sẻ → Thêm vào MH chính. Android: Chrome → menu → Cài đặt ứng dụng. Máy tính: biểu tượng cài đặt trên thanh địa chỉ.');}}><Download size={17}/>Cài Vua Tiếng Anh</button><p className="muted">Safari trên iPhone/iPad: Chia sẻ → Thêm vào màn hình chính. Giọng đọc và nhận diện tiếng nói có thể cần mạng.</p></section></div></>}
 {page==='about'&&<About/>}</>}
 <footer><span><Crown size={15}/>Vua Tiếng Anh <span className="footer-dot">·</span> Học một chút, tiến một bước.</span><button onClick={()=>go('about')}>Nguồn từ vựng & quyền riêng tư <ExternalLink size={13}/></button></footer></main></div>
 <nav className="mobile-bottom" aria-label="Điều hướng nhanh">{nav.filter(([id])=>['home','games','flashcards','review'].includes(id)).map(([id,label,I])=><button key={id} onClick={()=>go(id)} aria-label={label} className={page===id?'active':''}><I size={21}/><span>{id==='home'?'Khám phá':id==='games'?'Game':id==='flashcards'?'Thẻ từ':'Ôn tập'}</span></button>)}</nav>
 {notice&&<div className="toast" role="status"><span>{notice}</span><button aria-label="Đóng thông báo" onClick={()=>setNotice('')}><X size={17}/></button></div>}
 {selected&&<Modal title="Chi tiết từ vựng" close={()=>setSelected(null)}><WordDetail word={selected} state={state} favorite={()=>favorite(selected)} settings={state.settings} notify={notify}/><div className="detail-grade"><h3>Bạn nhớ từ này đến mức nào?</h3><RatingButtons onRate={r=>{save(s=>grade(s,selected.id,r));notify('Đã đánh giá từ và cập nhật lịch ôn.');setSelected(null);}}/></div></Modal>}
 {session&&<Session key={session.id} session={session} settings={state.settings} state={state} favorite={favorite} notify={notify} onGrade={(id,r)=>save(s=>grade(s,id,r))} complete={win=>{if(win&&session.mode==='adventure')save(s=>({...s,stage:Math.max(s.stage,session.stage+1)}));}} close={()=>{stopSpeech();setSession(null);}}/>}
 </div>;
}
function Stat({icon:I,color,value,label,sub,onClick}){const T=onClick?'button':'div';return <T className="stat-card" onClick={onClick}><span className={'stat-icon '+color}><I size={21}/></span><div><strong>{value}</strong><span>{label}</span><small>{sub}</small></div></T>;}
export function PageTitle({eyebrow,title,description}){return <div className="page-heading"><div><p className="eyebrow accent">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></div>;}
function JourneyMap({stage}){return <div className="journey-art" aria-label={'Bản đồ hành trình, hiện ở ải '+stage}><div className="map-grid"/><span className="map-cloud cloud-one"/><span className="map-cloud cloud-two"/><svg className="journey-path" viewBox="0 0 450 360" fill="none" aria-hidden="true"><path d="M65 280C180 310 65 170 200 198S355 245 315 126 370 90 392 56" stroke="#f6f0ff" strokeWidth="45" strokeLinecap="round"/><path d="M65 280C180 310 65 170 200 198S355 245 315 126 370 90 392 56" stroke="#b7a6e9" strokeWidth="2" strokeDasharray="7 9"/></svg><div className="map-island island-one"><TreePine size={38}/><TreePine size={52}/><TreePine size={30}/></div><div className="map-island island-two"><TreePine size={36}/><TreePine size={45}/></div><div className="map-station station-one"><span><Check size={25}/></span><b>Khởi hành</b></div><div className="map-station station-two"><span><Swords size={25}/></span><b>Ải {stage}</b><small>BẠN ĐANG Ở ĐÂY</small></div><div className="map-station station-three"><span><Flag size={25}/></span><b>Chân trời mới</b></div><div className="map-trophy"><Trophy size={40}/><span>Kho báu tri thức</span></div><div className="map-star star-one">✦</div><div className="map-star star-two">✧</div></div>;}
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function calendar(time){const [h,m]=time.split(':');const d=new Date();d.setHours(+h,+m,0,0);if(d<Date.now())d.setDate(d.getDate()+1);const stamp=d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')+'T'+h+m+'00';const created=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+/,'');download(['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//VuaTiengAnh//Study//VI','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:daily-study-'+Date.now()+'@vuatienganh','DTSTAMP:'+created,'DTSTART:'+stamp,'DURATION:PT15M','RRULE:FREQ=DAILY','SUMMARY:Học 15 phút cùng Vua Tiếng Anh','DESCRIPTION:Chơi một lượt game và ôn từ đến hạn.','BEGIN:VALARM','TRIGGER:-PT5M','ACTION:DISPLAY','DESCRIPTION:Đến giờ học tiếng Anh','END:VALARM','END:VEVENT','END:VCALENDAR',''].join('\r\n'),'nhac-hoc-tieng-anh.ics','text/calendar;charset=utf-8');}
