import React,{useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,ArrowRight,Volume2,Heart,Download,Upload,Check,Lock,RotateCcw,ShieldCheck} from 'lucide-react';
import {Modal,RatingButtons} from './Session';
import {speak,stopSpeech} from './speech';
import {shuffle} from './learning';
import {learnedPool,nextUnread,ebookDue,reviewOptions,answerText,speechText,ipaTokens} from './ebook-model';
import * as store from './ebook-store';
import './ebook.css';

const modes=[['flash','Lật thẻ ghi nhớ','Tự nhớ trước khi xem đáp án'],['meaning','Chọn nghĩa đúng','Tiếng Anh → tiếng Việt'],['english','Chọn cụm tiếng Anh','Tiếng Việt → tiếng Anh'],['write','Viết nghĩa tiếng Việt','Tự đối chiếu và đánh giá'],['spell','Điền cụm tiếng Anh','Nhớ lại cụm từ đã học'],['match','Ghép cặp trí nhớ','Ghép từ và nghĩa tương ứng']];
const labels={learn:'Đã học',rate:'Ôn tập',note:'Lưu ghi chú',favorite:'Đổi yêu thích',again:'Chưa nhớ',hard:'Hơi khó',good:'Nhớ rồi',easy:'Rất dễ'};
const date=t=>new Date(t).toLocaleString('vi-VN');
function download(data){const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`vua-ebook-a-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}

export default function Ebook({settings,notify}){
 const [book,setBook]=useState(null),[cards,setCards]=useState({}),[error,setError]=useState(''),[chapter,setChapter]=useState(0),[tab,setTab]=useState('learn'),[selected,setSelected]=useState(null),[practice,setPractice]=useState(null),[busy,setBusy]=useState(false),[log,setLog]=useState({entries:[],count:0}),[limit,setLimit]=useState(30),[persistent,setPersistent]=useState(null),[filter,setFilter]=useState(''),[onlyFav,setOnlyFav]=useState(false),[clock,setClock]=useState(Date.now());
 const input=useRef(),lock=useRef(false);
 useEffect(()=>{let active=true;Promise.all([fetch(import.meta.env.BASE_URL+'ebook-a.json').then(r=>{if(!r.ok)throw Error('Không tải được e-book.');return r.json();}),store.readCards()]).then(([b,c])=>{if(active){setBook(b);setCards(c);}}).catch(()=>setError('Chưa mở được dữ liệu hoặc bộ nhớ của thiết bị. Bật quyền lưu dữ liệu trang web và thử lại.'));navigator.storage?.persisted?.().then(setPersistent).catch(()=>{});const id=setInterval(()=>setClock(Date.now()),30000);const sync=()=>store.readCards().then(c=>active&&setCards(c)).catch(()=>{});window.addEventListener('focus',sync);return()=>{active=false;clearInterval(id);window.removeEventListener('focus',sync);stopSpeech();};},[]);
 useEffect(()=>{if(book)store.history(limit).then(setLog).catch(()=>{});},[cards,limit,book]);
 const words=book?.words||[],pool=useMemo(()=>learnedPool(words,cards),[words,cards]),due=useMemo(()=>ebookDue(words,cards,clock),[words,cards,clock]),next=nextUnread(words,cards),view=words.filter(w=>(!chapter||w.chapter===chapter)&&(!onlyFav||cards[w.id]?.favorite)&&(!filter||`${w.word} ${w.meaning}`.toLocaleLowerCase('vi').includes(filter.toLocaleLowerCase('vi'))));
 async function act(id,action){if(lock.current)return false;lock.current=true;setBusy(true);try{const c=await store.record(id,action);setCards(s=>({...s,[id]:c}));return true;}catch(e){notify(e.message||'Không lưu được. Hãy xuất bản sao và kiểm tra dung lượng thiết bị.');return false;}finally{lock.current=false;setBusy(false);}}
 function start(mode,dueOnly=false){const eligible=(dueOnly?due:pool).filter(w=>(!chapter||w.chapter===chapter)&&(!onlyFav||cards[w.id]?.favorite));if(!eligible.length){notify('Chưa có từ đã học trong nhóm này để ôn.');return;}if(['meaning','english','match'].includes(mode)&&new Set(eligible.map(w=>mode==='english'?w.word:w.meaning)).size<2){notify('Học ít nhất 2 từ có nghĩa khác nhau để chơi. Bạn vẫn có thể ôn flashcards.');return;}const unique=mode==='match'?eligible.filter((w,i,a)=>a.findIndex(x=>x.word===w.word||x.meaning===w.meaning)===i):eligible;setPractice({id:crypto.randomUUID(),mode,pool:eligible,deck:shuffle(unique).slice(0,mode==='match'?5:10)});}
 async function importFile(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;setBusy(true);try{await store.restore(JSON.parse(await f.text()),new Set(words.map(w=>w.id)));setCards(await store.readCards());notify('Đã hợp nhất bản sao e-book A; giữ lại lịch sử cũ và các ghi chú mới hơn.');}catch(e){notify(e.message||'Không nhập được bản sao.');}finally{setBusy(false);}}
 if(error)return <section className="empty"><h2>{error}</h2><button className="primary" onClick={()=>location.reload()}>Thử lại</button></section>;
 if(!book)return <section className="empty" aria-live="polite">Đang mở e-book A và tiến độ trên máy…</section>;
 return <div className="ebook-page">
  <section className="ebook-hero"><div><p className="eyebrow">YOUR PERSONAL BOOK • 15 CHỦ ĐỀ</p><h1>Học từ vựng<br/>qua e-book A</h1><p>Đi từng bước nhỏ. Hiểu từng cụm từ.<br/>Ghi nhớ lâu bằng những lần gặp lại.</p><button className="primary" disabled={!next} onClick={()=>setSelected(next)}>{next?'Tiếp tục học theo thứ tự':'Đã học hết e-book'}<ArrowRight size={18}/></button><small>{next?`Mục ${next.order+1}/${words.length} · ${book.chapters[next.chapter-1].name}`:'Hãy ôn tập để củng cố trí nhớ.'}</small></div><div className="ebook-cover" aria-hidden="true"><BookOpen size={48}/><span>THE VOCABULARY<br/>COLLECTION</span><strong>A</strong><span>IELTS NGUYỄN HUYỀN<br/>300 cụm chính + 526 mục học thêm</span></div></section>
  <div className="ebook-stats"><div><strong>{pool.length}<small> / {words.length}</small></strong><span>Mục đã học</span></div><div><strong>{due.length}</strong><span>Đến hạn ôn</span></div><div><strong>{log.count}</strong><span>Hoạt động được lưu</span></div><div><ShieldCheck/><span>Bộ nhớ riêng trên máy</span></div></div>
  <progress className="ebook-progress" aria-label="Tiến độ e-book A" value={pool.length} max={words.length}/>
  <div className="ebook-tabs" role="tablist" aria-label="E-book A">{[['learn','Lộ trình học'],['review','Ôn tập & trò chơi'],['memory','Bộ nhớ & lịch sử']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab!=='memory'&&<div className="ebook-toolbar"><label>Chủ đề<select aria-label="Chủ đề e-book" value={chapter} onChange={e=>setChapter(+e.target.value)}><option value="0">Tất cả 15 chủ đề</option>{book.chapters.map(c=><option key={c.id} value={c.id}>{c.id}. {c.name}</option>)}</select></label><label className="ebook-check"><input type="checkbox" checked={onlyFav} onChange={e=>setOnlyFav(e.target.checked)}/>Chỉ từ yêu thích</label>{tab==='learn'&&<label>Tìm trong sách<input placeholder="Từ hoặc nghĩa tiếng Việt…" value={filter} onChange={e=>setFilter(e.target.value)}/></label>}</div>}
  {tab==='learn'&&<><p className="ebook-hint">Học lần lượt cụm chính rồi đến các mục “Từ vựng học thêm”. Chỉ khi bấm <b>Đã học · Lưu và tiếp tục</b>, mục đó mới được đưa vào bài ôn. Từ chưa học phía sau vẫn khóa.</p><div className="ebook-chapters">{book.chapters.filter(c=>!chapter||chapter===c.id).map(c=>{const list=view.filter(w=>w.chapter===c.id),done=pool.filter(w=>w.chapter===c.id).length;return list.length>0&&<details key={c.id} open={!!chapter||c.id===(next?.chapter||1)}><summary><span className="ebook-chapter-number">{String(c.id).padStart(2,'0')}</span><span><b>{c.name}</b><small>{c.title} · Trang {c.page}</small></span><span>{done}/{words.filter(w=>w.chapter===c.id).length}</span></summary><div className="ebook-word-list">{list.map(w=>{const unlocked=!!cards[w.id]?.learnedAt||w.id===next?.id;return <button key={w.id} disabled={!unlocked} onClick={()=>setSelected(w)} className={cards[w.id]?.learnedAt?'is-learned':''}><span className="ebook-order">{w.order+1}</span><span><b lang="en">{w.word}</b><small>{w.kind==='main'?`Cụm chính ${w.number}`:`Học thêm · cụm ${w.number}`} · Trang {w.page}{cards[w.id]?.favorite?' · ♥':''}</small></span>{cards[w.id]?.learnedAt?<Check size={18}/>:unlocked?<ArrowRight size={18}/>:<Lock size={15}/>}</button>;})}</div></details>;})}</div>{!view.length&&<p className="empty">Không có từ phù hợp với bộ lọc.</p>}</>}
  {tab==='review'&&<><div className="ebook-review-intro"><div><h2>Gặp lại những từ đã học.</h2><p>Câu hỏi và mọi phương án trả lời đều nằm trong bộ từ bạn đã học của e-book A. Mỗi lần đánh giá sẽ cập nhật lịch ôn riêng.</p></div><button className="primary" disabled={!due.length} onClick={()=>start('flash',true)}><RotateCcw size={17}/>Ôn từ đến hạn ({due.length})</button></div><div className="ebook-games">{modes.map(([id,name,desc],i)=><button key={id} className={'ebook-game tone-'+i} disabled={!pool.length} onClick={()=>start(id)}><span>0{i+1}</span><h3>{name}</h3><p>{desc}</p><small>Tối đa {id==='match'?5:10} từ đã học <ArrowRight size={15}/></small></button>)}</div>{!pool.length&&<p className="ebook-hint">Hoàn thành mục đầu tiên trong lộ trình để mở flashcards và bài luyện viết. Trắc nghiệm và ghép cặp mở khi có ít nhất 2 từ khác nhau đã học.</p>}</>}
  {tab==='memory'&&<><section className="ebook-memory"><h2>Hành trình này nằm trên thiết bị của bạn.</h2><p>Tiến độ, mức độ nhớ, lịch ôn, yêu thích, ghi chú và từng lần học được lưu trong bộ nhớ riêng của trình duyệt này. Đóng trang rồi mở lại vẫn học tiếp được. Dữ liệu e-book tách riêng khỏi bộ 3.000 từ.</p><div className="ebook-actions"><button className="primary" onClick={()=>store.backup().then(download).catch(()=>notify('Không xuất được bản sao.'))}><Download size={17}/>Xuất bản sao e-book A</button><button className="soft-button" disabled={busy} onClick={()=>input.current.click()}><Upload size={17}/>Nhập bản sao</button><input hidden ref={input} type="file" accept=".json,application/json" onChange={importFile}/><button className="soft-button" onClick={async()=>{try{const ok=await navigator.storage?.persist?.();setPersistent(!!ok);notify(ok?'Trình duyệt đã cấp lưu trữ bền vững.':'Trình duyệt chưa cấp lưu trữ bền vững; hãy xuất bản sao định kỳ.');}catch{notify('Trình duyệt không hỗ trợ yêu cầu này.');}}}>Ưu tiên giữ dữ liệu trên máy</button></div><p className="ebook-hint">{persistent?'Đã được cấp lưu trữ bền vững. ':''}Mỗi thiết bị, trình duyệt và địa chỉ website có bộ nhớ khác nhau. Dùng cùng địa chỉ Vercel để học tiếp. Không dùng chế độ ẩn danh. Xóa dữ liệu trình duyệt hoặc đổi máy có thể làm mất tiến độ; xuất bản sao để chuyển máy hoặc khôi phục. Lịch sử tăng theo việc học thực tế, trong giới hạn dung lượng thiết bị.</p></section><section className="ebook-history"><h2>Lịch sử học · {log.count} hoạt động</h2>{!log.count&&<p>Bắt đầu học để lưu hoạt động đầu tiên.</p>}<ol>{log.entries.map(e=><li key={e.id}><span><b>{labels[e.type]}{e.rating?` · ${labels[e.rating]}`:''}</b><small lang="en">{words.find(w=>w.id===e.wordId)?.word}</small>{e.type==='note'&&e.value&&<p>{e.value}</p>}</span><time>{date(e.at)}</time></li>)}</ol>{log.count>log.entries.length&&<button className="soft-button" onClick={()=>setLimit(n=>n+30)}>Xem thêm lịch sử</button>}</section></>}
  <details className="ebook-source"><summary>Nguồn sách, phiên âm & ghi chú biên tập</summary><p>{book.source} · {book.sourceFile} · 114 trang. Đã nhập 300 cụm chính và 526 mục học thêm, giữ thứ tự và các mục lặp theo ngữ cảnh. Ví dụ và nghĩa lấy từ sách; bài ôn tương tác được tạo từ các mục đã học.</p><p>Sách không cung cấp IPA hay bản thu âm. IPA bổ sung từ open-dict-data/ipa-dict (MIT), hiển thị theo từng từ, không phải phiên âm nối âm của cả câu. Một số từ chỉ có một giọng hoặc chưa có IPA; app ghi rõ. Giọng đọc tổng hợp dùng giọng tiếng Anh có trên máy; chất lượng và khả năng nghe ngoại tuyến phụ thuộc thiết bị. Không thể cam kết chính xác 100% trên mọi thiết bị.</p><ul>{words.filter(w=>w.editorNote).map(w=><li key={w.id}>Trang {w.page}: {w.editorNote}</li>)}</ul></details>
  {selected&&<Modal title={`E-book A · Mục ${selected.order+1}/${words.length}`} close={()=>{stopSpeech();setSelected(null);}}><Study key={selected.id} word={selected} book={book} card={cards[selected.id]} settings={settings} notify={notify} busy={busy} act={act} advance={async(note)=>{if(note!==(cards[selected.id]?.note||'')&&!await act(selected.id,{type:'note',value:note}))return;if(await act(selected.id,{type:'learn'})){const n=words[selected.order+1];setSelected(n||null);}}}/></Modal>}
  {practice&&<Practice key={practice.id} session={practice} book={book} settings={settings} notify={notify} busy={busy} rate={(id,rating)=>act(id,{type:'rate',rating})} close={()=>{stopSpeech();setPractice(null);}}/>}
 </div>;
}

function Audio({text,settings,notify,label='Nghe cụm từ'}){return <button className="soft-button" onClick={()=>speak(speechText(text),settings,notify)}><Volume2 size={17}/>{label}</button>;}
function Pronunciation({word,book,settings,notify}){return <details className="ebook-ipa"><summary>Phiên âm từng từ · Anh–Anh / Anh–Mỹ</summary><p>Tra từng từ độc lập; trọng âm câu và nối âm sẽ khác. Bấm từng từ để nghe.</p><div>{ipaTokens(word.word).map((t,i)=>{const p=book.pronunciation[t.toLowerCase()]||{};return <button key={i} onClick={()=>speak(t,settings,notify)}><b>{t}</b><span>UK {p.uk||'chưa có IPA'}</span><span>US {p.us||'chưa có IPA'}</span></button>;})}</div></details>;}
function Meaning({word:w,settings,notify}){return <div className="ebook-meaning"><h3>{w.meaning}</h3><div className="example-box"><span>{w.kind==='extra'?'NGỮ CẢNH CỦA CỤM CHÍNH TRONG SÁCH':'VÍ DỤ TRONG SÁCH'}</span><p lang="en">{w.example}</p><p className="translation">{w.exampleVi}</p><Audio text={w.example} settings={settings} notify={notify} label="Nghe câu ví dụ"/></div>{w.editorNote&&<p className="ebook-hint">Ghi chú: {w.editorNote}</p>}</div>;}
function Study({word:w,book,card,settings,notify,busy,act,advance}){
 const [revealed,setRevealed]=useState(false),[note,setNote]=useState(card?.note||'');
 return <div className="ebook-study"><p className="eyebrow">{book.chapters[w.chapter-1].name} · Trang {w.page} · {w.kind==='main'?'Cụm chính':'Từ vựng học thêm'}</p><h2 lang="en">{w.word}</h2><div className="ebook-actions"><Audio text={w.word} settings={settings} notify={notify}/><button className="soft-button" disabled={busy} onClick={()=>act(w.id,{type:'favorite'})}><Heart size={17} fill={card?.favorite?'currentColor':'none'}/>{card?.favorite?'Đã yêu thích':'Yêu thích'}</button></div><Pronunciation word={w} book={book} settings={settings} notify={notify}/>{!revealed?<button className="ebook-reveal" onClick={()=>setRevealed(true)}>Lật thẻ · Xem nghĩa và ví dụ</button>:<><Meaning word={w} settings={settings} notify={notify}/><label className="ebook-note">Ghi nhớ riêng của tôi<textarea maxLength={10000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Mẹo nhớ, liên tưởng hoặc câu ví dụ của bạn…"/></label><button className="soft-button" disabled={busy} onClick={async()=>{if(await act(w.id,{type:'note',value:note}))notify('Đã lưu ghi chú trên thiết bị.');}}>Lưu ghi chú riêng</button><div className="ebook-continue"><button className="primary" disabled={busy} onClick={()=>advance(note)}>{busy?'Đang lưu…':'Đã học · Lưu và tiếp tục'}<ArrowRight size={17}/></button><small>{card?.learnedAt?`Đã học ${date(card.learnedAt)} · Hạn ôn ${date(card.due)}`:'Sau khi lưu, mục này mới xuất hiện trong bài ôn.'}</small></div></>}</div>;
}

function Practice({session:s,book,settings,notify,busy,rate,close}){
 const [index,setIndex]=useState(0),[revealed,setRevealed]=useState(false),[answer,setAnswer]=useState(''),[result,setResult]=useState(null),[score,setScore]=useState(0),[finished,setFinished]=useState(false),[left,setLeft]=useState(null),[matched,setMatched]=useState([]),[pairError,setPairError]=useState('');
 const guard=useRef(false),w=s.deck[index],mode=s.mode,options=useMemo(()=>reviewOptions(w,s.pool,mode==='english'?'word':'meaning'),[w,s.pool,mode]),right=useMemo(()=>shuffle(s.deck),[s.id]);
 function next(){stopSpeech();if(index+1>=s.deck.length)setFinished(true);else{setIndex(i=>i+1);setRevealed(false);setAnswer('');setResult(null);guard.current=false;}}
 async function grade(r){if(guard.current||busy)return;guard.current=true;if(await rate(w.id,r)){if(r!=='again')setScore(n=>n+1);next();}else guard.current=false;}
 async function choose(v){if(result!==null||guard.current||busy)return;guard.current=true;const correct=v===(mode==='english'?w.word:w.meaning);if(await rate(w.id,correct?'good':'again')){setResult(correct);if(correct)setScore(n=>n+1);}else guard.current=false;}
 async function pair(r){if(!left||matched.includes(r.id)||guard.current||busy)return;guard.current=true;const correct=left.id===r.id;if(await rate(left.id,correct?'good':'again')){if(correct){const ids=[...matched,left.id];setMatched(ids);setPairError('');if(ids.length===s.deck.length){setScore(ids.length);setFinished(true);}}else setPairError('Chưa khớp. Hãy thử ghép lại cặp vừa chọn.');setLeft(null);}guard.current=false;}
 return <Modal title={`E-book A · ${modes.find(m=>m[0]===mode)[1]}`} close={close}><div className="ebook-practice">{finished?<div className="ebook-finished"><Check size={48}/><h2>Đã lưu lượt ôn trên máy</h2><p>{mode==='match'?`Đã ghép ${s.deck.length} cặp.`:`${score}/${s.deck.length} mục được đánh giá nhớ.`}</p><p>Từ chưa nhớ sẽ được nhắc ôn lại sau 10 phút.</p><button className="primary" onClick={close}>Về e-book A</button></div>:<><p className="eyebrow">CHỈ TỪ ĐÃ HỌC · {mode==='match'?`${matched.length}/${s.deck.length} cặp`:`${index+1}/${s.deck.length}`}</p>{mode==='match'?<><div className="ebook-pairs"><div>{s.deck.map(t=><button key={t.id} className={left?.id===t.id?'selected':''} disabled={busy||matched.includes(t.id)} onClick={()=>setLeft(t)}>{t.word}</button>)}</div><div>{right.map(t=><button key={t.id} disabled={busy||!left||matched.includes(t.id)} onClick={()=>pair(t)}>{t.meaning}</button>)}</div></div><p role="status">{pairError}</p></>:<><h2 lang={mode==='english'||mode==='spell'?'vi':'en'}>{mode==='english'||mode==='spell'?w.meaning:w.word}</h2>{mode!=='english'&&mode!=='spell'&&<Audio text={w.word} settings={settings} notify={notify}/>}<p className="ebook-hint">{book.chapters[w.chapter-1].name} · Trang {w.page}</p>{['meaning','english'].includes(mode)?<><div className="ebook-options">{options.map(t=><button key={t.id} disabled={busy||result!==null} onClick={()=>choose(mode==='english'?t.word:t.meaning)}>{mode==='english'?t.word:t.meaning}</button>)}</div>{result!==null&&<div className="ebook-feedback" role="status"><b>{result?'Chính xác!':'Chưa đúng — xem lại nhé.'}</b><p>{w.word} → {w.meaning}</p><Meaning word={w} settings={settings} notify={notify}/><button className="primary" onClick={next}>{index+1===s.deck.length?'Xem kết quả':'Tiếp theo'}</button></div>}</>:<>{mode!=='flash'&&!revealed&&<label className="ebook-note">{mode==='write'?'Nghĩa tiếng Việt bạn nhớ':'Cụm tiếng Anh bạn nhớ'}<textarea value={answer} onChange={e=>setAnswer(e.target.value)} autoComplete="off" spellCheck={false}/></label>}{!revealed?<button className="ebook-reveal" disabled={mode!=='flash'&&!answer.trim()} onClick={()=>setRevealed(true)}>{mode==='flash'?'Lật thẻ · Xem đáp án':'Đối chiếu đáp án'}</button>:<><h3 lang="en">{w.word}</h3>{mode!=='flash'&&<p className="ebook-hint">{answerText(answer)===answerText(mode==='write'?w.meaning:w.word)?'Khớp với đáp án trong sách.':'Đối chiếu bên dưới. Cách diễn đạt tương đương vẫn có thể đúng; hãy tự đánh giá, app không chấm sai chỉ vì khác câu chữ.'}</p>}<Meaning word={w} settings={settings} notify={notify}/><p>Bạn nhớ ở mức nào?</p><fieldset disabled={busy} className="ebook-rating"><RatingButtons onRate={grade}/></fieldset></>}</>}</>}</>}</div></Modal>;
}
