let currentAudio=null;
export function stopSpeech(){window.speechSynthesis?.cancel();if(currentAudio){currentAudio.pause();currentAudio=null;}}
export function speak(text,settings,onStatus=()=>{}){
 stopSpeech();const synth=window.speechSynthesis;
 if(!synth){onStatus('Thiết bị chưa có giọng đọc. Hãy dùng Safari, Chrome hoặc Edge mới.');return false;}
 const voices=synth.getVoices(),locale=settings.accent;
 const matches=voices.filter(v=>v.lang.replace('_','-').toLowerCase()===locale.toLowerCase());
 const voice=matches.find(v=>/Google|Natural|Samantha|Daniel|Microsoft/i.test(v.name))||matches[0];
 const english=voice||voices.find(v=>/^en[-_]/i.test(v.lang));
 if(!english){onStatus('Chưa có giọng tiếng Anh. Hãy cài giọng English trong cài đặt thiết bị, rồi thử lại.');return false;}
 if(!voice)onStatus('Máy chưa có giọng theo vùng đã chọn; đang dùng '+english.lang+'. Có thể cài thêm giọng trong cài đặt thiết bị.');
 const u=new SpeechSynthesisUtterance(text);u.lang=english.lang;u.voice=english;u.rate=settings.rate;u.pitch=1;u.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))onStatus('Không phát được âm thanh. Hãy chạm Nghe lại hoặc kiểm tra âm lượng.');};synth.speak(u);return true;
}
export const IPA_GUIDE=[['iː','see','/siː/','Kéo dài âm, môi hơi căng.'],['ɪ','sit','/sɪt/','Âm ngắn, lưỡi thả lỏng hơn /iː/.'],['æ','cat','/kæt/','Mở hàm rộng, lưỡi ở phía trước.'],['ʌ','cup','/kʌp/','Âm ngắn, miệng thả lỏng.'],['ɑː','father','/ˈfɑːðə/','Mở miệng, kéo dài âm.'],['ɒ','hot','/hɒt/','Anh–Anh: tròn môi, âm ngắn.'],['ɔː','thought','/θɔːt/','Tròn môi và kéo dài âm.'],['ʊ','book','/bʊk/','Âm ngắn, môi tròn nhẹ.'],['uː','food','/fuːd/','Môi tròn, kéo dài âm.'],['ə','about','/əˈbaʊt/','Schwa: rất nhẹ, không mang trọng âm.'],['ɜː','bird','/bɜːd/','Anh–Anh: âm dài, lưỡi ở giữa.'],['e','bed','/bed/','Âm ngắn, mở miệng vừa.'],['eɪ','day','/deɪ/','Chuyển từ /e/ về /ɪ/.'],['aɪ','time','/taɪm/','Chuyển từ /a/ về /ɪ/.'],['ɔɪ','boy','/bɔɪ/','Chuyển từ /ɔ/ về /ɪ/.'],['aʊ','now','/naʊ/','Chuyển từ /a/ về /ʊ/.'],['əʊ','go','/ɡəʊ/','Anh–Anh: chuyển từ /ə/ về /ʊ/.'],['ɪə','near','/nɪə/','Anh–Anh: kết thúc bằng /ə/.'],['eə','hair','/heə/','Anh–Anh: thường cũng đọc là nguyên âm dài /ɛː/.'],['ʊə','tour','/tʊə/','Anh–Anh: có biến thể /ɔː/.'],['θ','think','/θɪŋk/','Đặt đầu lưỡi nhẹ giữa hai hàm răng, thổi hơi.'],['ð','this','/ðɪs/','Giống /θ/ nhưng dây thanh rung.'],['ʃ','she','/ʃiː/','Môi hơi tròn, hơi đi qua khe hẹp.'],['ʒ','vision','/ˈvɪʒən/','Giống /ʃ/ nhưng dây thanh rung.'],['tʃ','chair','/tʃeə/','Bắt đầu bằng /t/, rồi thả thành /ʃ/.'],['dʒ','job','/dʒɒb/','Bắt đầu bằng /d/, rồi thả thành /ʒ/.'],['ŋ','sing','/sɪŋ/','Âm mũi, không thêm /ɡ/ ở cuối sing.'],['p','pen','/pen/','Hai môi bật mở, không rung thanh.'],['b','bad','/bæd/','Hai môi bật mở, có rung thanh.'],['t','tea','/tiː/','Đầu lưỡi chạm vùng lợi sau răng trên.'],['d','day','/deɪ/','Giống /t/ nhưng có rung thanh.'],['k','key','/kiː/','Phần sau lưỡi bật khỏi ngạc mềm.'],['ɡ','go','/ɡəʊ/','Giống /k/ nhưng có rung thanh.'],['f','fine','/faɪn/','Răng trên chạm nhẹ môi dưới, thổi hơi.'],['v','very','/ˈveri/','Giống /f/ nhưng có rung thanh.'],['s','see','/siː/','Thổi hơi qua khe hẹp, không rung thanh.'],['z','zoo','/zuː/','Giống /s/ nhưng có rung thanh.'],['h','hat','/hæt/','Thở nhẹ, không chặn luồng hơi.'],['m','man','/mæn/','Khép môi, đưa âm qua mũi.'],['n','no','/nəʊ/','Lưỡi chạm lợi trên, âm qua mũi.'],['l','light','/laɪt/','Đầu lưỡi chạm lợi, hơi qua hai bên.'],['r','red','/red/','Không rung đầu lưỡi như r tiếng Việt.'],['j','yes','/jes/','Lưỡi ở phía trước, lướt nhanh.'],['w','we','/wiː/','Tròn môi rồi mở nhanh.']];
